# Generated by Django 5.0.2 on 2024-04-12 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='place',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='branch',
            field=models.ForeignKey(default=1, max_length=355, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
            preserve_default=False,
        ),
    ]
