# Generated by Django 5.0.4 on 2024-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_testimonial_place_testimonial_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
