# Generated by Django 5.0.4 on 2024-04-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_payment_date_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
